#server:
#  port: 8014
#spring:
#  application:
#    name: api-order-submit
#  redis:
#    port: 7001
#    host: 47.96.11.185
#    database: 0
#    password: qfedu123
#  rabbitmq:
#    host: 47.96.11.185
#    port: 5672
#    virtual-host: host1
#    username: zhangsan
#    password: admin123
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1
#eureka:
#  client:
#    service-url:
#      defaultZone: http://zhangsan:123456@localhost:8761/eureka
#
#feign:
#  hystrix:
#    enabled: true

spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: api-order-submit
      label: master
