
server:
  port: 8002
spring:
  application:
    name: api-user-regist
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka


feign:
  hystrix:
    enabled: true